theme: jekyll-theme-cayman
title: Patrick Tran
description: "UCLA Statistics Graduate | COOP Data Analytics Fellow | 8+ Years of Creative Project Management"
url: "https://pktrance.github.io/Portfolio/"
plugins:
  - jekyll-seo-tag
